# Generated by Django 3.2.7 on 2021-09-16 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='departure_time',
            field=models.TimeField(default=datetime.time),
        ),
        migrations.AlterField(
            model_name='access',
            name='entry_time',
            field=models.TimeField(default=datetime.time),
        ),
    ]
