# Generated by Django 3.2.7 on 2021-09-17 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0005_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
