# Generated by Django 3.2.7 on 2021-09-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0006_alter_access_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
